### model
model_name_or_path: path_to_trained_ppo_model
reward_model: path_to_trained_reward_model
trust_remote_code: true

### method
stage: ppo
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all

# Add these new parameters
#min_reward_threshold: 1.0  # Set your desired alpha value here
#key_loss_weight: 0.7      # Set your desired beta value here

### dataset
dataset: regal_IL_TUR_ppo_data
template: llama3
cutoff_len: 2048
max_samples: 8000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/lora/ppo
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### generate
max_new_tokens: 512
top_k: 0
top_p: 0.9
